---
title: "Build your own personal website starting with Hugo"
author: "Liu Shansong"
date: '`r format(Sys.Date(), "%Y-%m-%d")`'
categories: ["Web Development"]
tags: ["Web Technique"]
output: html_document
---

## Introduction of Hugo
Unlike other frameworks like [Jekyll][1] and [Hexo][2], which are developed for personal blog building, **[Hugo][3]** is a general-purpose website framework, also a static site generator. Hugo is developed by [Go][4] language and has a very fast responsive speed. I chose Hugo because it allows the author to post not only blogs but also some other things like docs, portfolios, etc. Hope you will enjoy Hugo just like me!

## Installing Hugo
Installation is very easy. Simply download the appropriate version for your platform from [Hugo Releases][5].
If you use open source system like Linux, you had better put the extracted excutable file in the `/usr/local/bin` location and add it to your `PATH` variable.
On macOS, if you have [Homebrew][6], just run `brew update && brew install hugo`. Here is a detail instruction for [macOS installation][7] made by the Hugo's author.
For windows users, please see [Installation on Windows][8].
You can test Hugo while you installed it with `hugo help` in a command prompt window.
For a complete knowledge of Hugo, please visit the author's [Hugo docs][9] website.

## Build your personal website with Hugo, Blogdown and Github Pages
Suppose you want to create a blog like what I am writing, first you can use the following command to create a local repository.



[1]: https://jekyllrb.com/                              "Jekyll"
[2]: https://hexo.io/                                   "Hexo"
[3]: http://gohugo.io                                   "Hugo"
[4]: https://golang.org/                                "Go language"
[5]: https://github.com/spf13/hugo/releases             "Hugo releases"
[6]: https://brew.sh/                                   "Homebrew"
[7]: http://gohugo.io/tutorials/installing-on-mac/      "macOS installation of Hugo"
[8]: http://gohugo.io/tutorials/installing-on-windows/  "windows installation of Hugo"
[9]: http://gohugo.io/overview/introduction/            "Hugo docs"